# Generated by Django 6.0.5 on 2026-06-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('username', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
            ],
        ),
    ]
