# Generated by Django 6.0.5 on 2026-06-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingapproval',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingapproval',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
