# Generated by Django 6.0.5 on 2026-06-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVIEW', 'Review'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
