# Generated by Django 6.0.5 on 2026-07-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
